### ISSUE TITLE
Should this line be pt_samples[3,:] instead of pt_samples[3,0]?

### ISSUE THREAD

**Issue by jma100** [leomariga/pyRANSAC-3D#14]
https://github.com/leomariga/pyRANSAC-3D/blob/28b0735a548ca52ed39a7fcd312353d1eec084a6/pyransac3d/cuboid.py#L73

**Comment by leomariga** [comment]
Yes. 
This was working because the plane is infinite and and the points are random, in some way it was working with this error. I'm really surprised, thank you for letting us know.

**Comment by leomariga** [comment]
Fix on 0ae8e71
