### ISSUE TITLE
Bad plane fitting (maybe bad parameter)

### ISSUE THREAD

**Issue by LexQzim** [leomariga/pyRANSAC-3D#18]
Hey, 

I would like to attach a plane equation to a point cloud in order to be able to compare new point clouds with the plane later. 

At first it looked fine, but over time I noticed that my plane equation is always aligned parallel to the Z-plane. As can be seen here: 
![Image Pasted at 2021-3-9 13-15](https://user-images.githubusercontent.com/12845370/110649387-d3f65080-81b9-11eb-9249-f6bf45cf3096.png)
My plan equation parameter = [0,0,1,-832]

This is my code: 
`
planeObj = pyrsc.Plane()
    best_eq, best_inliers = planeObj.fit(pointCloudPoints, thresh=0.001, minPoints=1000, maxIteration=10000)
`
    
I'm using round about 200k points for the fitting. 

Now I am not sure if I have set my parameters correctly and hope that you can help me here. 

For comparison, here is a picture with a different RANSAC algorithm:
![Image Pasted at 2021-3-9 13-18](https://user-images.githubusercontent.com/12845370/110649407-d9539b00-81b9-11eb-8a04-253456b8a426.png)
Here are the plane equationparameter = [-2.62341300e-05  4.57572034e-05 -1.20127911e-03  9.99999277e-01]
This code I code from here [https://github.com/falcondai/py-ransac]()

I hope you have a tip for me. 

Thank you.

**Comment by leomariga** [comment]
Try increasing the value of thresh=0.001, to thresh=1. This means the distance from the plane equation to be considered inliers. You have to choose a value related to the error deviation from your point cloud. 

If it doesn't work, please let me know so I can make some tests here. Do you have the point coordinates?

**Comment by LexQzim** [comment]
Ok, sorry that was definitely my fault. I somehow missunterstood the threshold value. 

Thank you for your help, this solves my problem.
