### ISSUE TITLE
RANSAC Plane from 3 and 4 points fails

### ISSUE THREAD

**Issue by ardiya** [leomariga/pyRANSAC-3D#22]
Currently Ransac Plane fails when total of the provided points is 3 or 4.

Reproducible code
```
import pyransac3d as pyrsc
import numpy as np

plane = pyrsc.Plane()
pts = [[0,0,0],[0,1,0],[1,0,0]]
plane.fit(np.array(pts), 0.01)
```

And it receives error:
```
File "<stdin>", line 1, in <module>
  File "/home/ardiya/.local/lib/python3.8/site-packages/pyransac3d/plane.py", line 46, in fit
    id_samples = random.sample(range(1, n_points-1), 3)
  File "/usr/lib/python3.8/random.py", line 363, in sample
    raise ValueError("Sample larger than population or is negative")
ValueError: Sample larger than population or is negative
```

Env note:
pyransac3d 0.5.1 from pip install

**Comment by ardiya** [comment]
Thanks @leomariga ! When you're free, could you also update the pypi/pip package please?

**Comment by leomariga** [comment]
@ardiya Thank you very much for opening this issue! 

Yes, I'm releasing a new version as soon as possible. I'm waiting for my computer arrive from maintenance. I'll believe I can do it until next Sunday, on worst case scenario.
