### ISSUE TITLE
Disable printing the number of points

### ISSUE THREAD

**Issue by MrPositron** [leomariga/pyRANSAC-3D#25]
I have thousands of shapes, and I don't want the fitting function to print the number of points for each shape. Could you disable that option?

Thanks in advance!

**Comment by leomariga** [comment]
Hi @MrPositron, thank you for your message. 
I believe this issue was solved on #19 . 
Do you know which primitive figure is printing the number of points?

Thanks

**Comment by MrPositron** [comment]
I was fitting planes, and I installed it using `pip`

**Comment by MrPositron** [comment]
I built `pyransac3d` from the latest commit and everything works fine. Seems that pip version is not right. Thanks!

**Comment by leomariga** [comment]
I'll update the next version of pip next Sunday =)
The new version will have many improvements. 
If you find something else to change, or have a suggestion, feel free to create another issue. 
Thanks!

**Comment by leomariga** [comment]
Hey, 0.6.0 is out. Now without the prints.
